id: P007923
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS60392
  title: བླ་མ་དགོངས་པ་འདུས་པ་ལས༔་སྔོན་འགྲོ་ཆོས་སྤྱོད་སོགས་ཀྱི་སྐོར
  author: ''
  volumes:
    c29924c734864551b73549e89252d94b:
      image_group_id: I1GS60394
      title: 'Volume 1 of bla ma dgongs pa ''dus pa las: sngon ''gro chos spyod sogs
        kyi skor'
      volume_number: 1
      total_pages: 346
      base_file: v001.txt
ebook_metadata:
  title: བླ་མ་དགོངས་པ་འདུས་པ་ལས༔་སྔོན་འགྲོ་ཆོས་སྤྱོད་སོགས་ཀྱི་སྐོར
  author: ''
  sku: P007923
  cover: cover.jpg
  layers:
  - pagination
