id: P007923
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS60392
  title: བླ་མ་དགོངས་པ་འདུས་པ་ལས༔་སྔོན་འགྲོ་ཆོས་སྤྱོད་སོགས་ཀྱི་སྐོར
  author: ''
  volumes:
    691cfe686ca343cfb1e1bfda6ae427ee:
      image_group_id: I1GS60394
      title: ''
      volume_number: 1
      total_pages: 346
ebook_metadata:
  title: བླ་མ་དགོངས་པ་འདུས་པ་ལས༔་སྔོན་འགྲོ་ཆོས་སྤྱོད་སོགས་ཀྱི་སྐོར
  author: ''
  sku: P007923
  cover: cover.jpg
  layers:
  - pagination
