id: P007923
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:49:28.971214
source_metadata:
  id: bdr:W1GS60392
  title: བླ་མ་དགོངས་པ་འདུས་པ་ལས༔་སྔོན་འགྲོ་ཆོས་སྤྱོད་སོགས་ཀྱི་སྐོར
  author: ''
  volumes:
    c29924c734864551b73549e89252d94b:
      image_group_id: I1GS60394
      title: 'Volume 1 of bla ma dgongs pa ''dus pa las: sngon ''gro chos spyod sogs
        kyi skor'
      volume_number: 1
      total_pages: 346
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
